### ISSUE TITLE
Cannot enter username or password

### ISSUE THREAD

**Issue by StephanEggermont** [JurajKubelka/PharoSprint#16]
PharoSprint32bit-60469-20170424-89
Windows

**Comment by JurajKubelka** [comment]
Hi @StephanEggermont,

thank you for the testing! Is it the same issue as #15 (see the attached screenshot)?

**Comment by StephanEggermont** [comment]
No. The text is not editable

**Comment by JurajKubelka** [comment]
@StephanEggermont: I have tested it on Windows 7 Professional Service Pack 1 and it works. I have no idea how to reproduce the issue. Do you use a specific Pharo or OS preference that can influence this behavior?

**Comment by StephanEggermont** [comment]
Hmm. Some initialization issue. After looking at it again (few hours later) I could login. Could it be waiting for some connection? I'm on a corporate network here. Pretty long ping times to Chile

**Comment by JurajKubelka** [comment]
I am rewriting the Spec UI part in order to solve #15. So we can test it later again.
