### ISSUE TITLE
Application blocks on dragging an issue to in progress

### ISSUE THREAD

**Issue by StephanEggermont** [JurajKubelka/PharoSprint#19]
When dragging an issue to in progress, the ui is only updated after the state change is confirmed. That makes for a bad UI experience. It would be good to introduce a visible state for dragged to in progress but no response received yet, so as to not block the gui.

**Comment by JurajKubelka** [comment]
Hi @StephanEggermont,

today, I has slow Internet connection and I have experienced what you mention. Well, this is generic problem of all Pharo applications as they run all code in the UI process. Pharo Sprint runs FogBugz commands in a separate process, but not Discord and MQTT connections. I will improve this for the next release.
