### ISSUE TITLE
Opening an issue on Fogbuz by double clicking?

### ISSUE THREAD

**Issue by bergel** [JurajKubelka/PharoSprint#27]
Opening an issue on Fogbugz I the most frequent action I do. However, doing this action takes time (i.e., right-click, and then click on an item). Why not double clicking on an issue to open it on Fogbugz?

**Comment by JurajKubelka** [comment]
I do not like the double click because it is not intuitive. 
But if it is supported by Glamour, we can add it for now.

**Comment by JurajKubelka** [comment]
Glamour example for double click action:

```Smalltalk

browser := GLMTabulator new.
browser column: #one.
browser transmit to: #one; andShow: [ :a |
	a fastList 
		title: 'List';
		onChangeOfPort: #strongSelection 
			act: [ :presentation :entity | self inform: 'STRONG selection on ', presentation strongSelection asString ] ].

browser openOn: Object allSubclasses  
```

**Comment by bergel** [comment]
Excellent!
