### ISSUE TITLE
Commit changes?

### ISSUE THREAD

**Issue by bergel** [JurajKubelka/PharoSprint#28]
Not sure what the following does:
<img width="357" alt="screen shot 2017-04-28 at 11 22 10 am" src="https://cloud.githubusercontent.com/assets/393742/25522931/11153314-2c05-11e7-9bbc-02169dfcd50b.png">

Is the `Commit changes` menu entry creates the slice?

**Comment by bergel** [comment]
Maybe there is a tool tip comment that can be inserted ?

**Comment by JurajKubelka** [comment]
`Commit changes` opens Monticello and SliceMaker, and copy the case number to the clipboard.

All context actions has a tool tip. They are not displayed for some reason. Likely a missing feature in Glamour. I will investigate it.
