### ISSUE TITLE
Maybe we need a fourth pane with to be reviewed

### ISSUE THREAD

**Issue by bergel** [JurajKubelka/PharoSprint#3]
For example, Miguel and Jose Esteban are currently reviewing 18028. But this cannot be said on the sprint tool

**Comment by JurajKubelka** [comment]
Are you talking about a case that is in "done" list? Then you are right. Maybe it can be solved by adding "solving" and "reviewing" state for taken cases and by introducing more contributors for one case #2.

**Comment by JurajKubelka** [comment]
solved by adding 'review case' menu item into the done list, see 23eac4dc42f9c5cdec60bfbb971c7355e801ed5b
