### ISSUE TITLE
Name of an issue is not accessible if too long

### ISSUE THREAD

**Issue by bergel** [JurajKubelka/PharoSprint#4]
I cannot get the full name of issue 18269
![screen shot 2017-03-31 at 12 22 24 pm](https://cloud.githubusercontent.com/assets/393742/24557054/bab75c62-160c-11e7-8d11-66e4ea70b466.png)

**Comment by JurajKubelka** [comment]
solved by removing of the details part below and by adding a "status bar" that displays whole name
